version: '3'

services:
  redis:
    image: redis:4.0-alpine
    ports:
      - 6379
    networks:
      - knet

  web:
    image: chebykin/keksplorer-web:latest
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - WS_API_URL=http://docker.for.mac.localhost:8546
      - REDIS_URL=redis://redis:6379/0
    networks:
      - knet

  agent:
    image: chebykin/keksplorer-agent:latest
    depends_on:
      - redis
    environment:
      - WS_API_URL=http://docker.for.mac.localhost:8546
      - REDIS_URL=redis://redis:6379/0
    networks:
      - knet

  worker:
    image: chebykin/keksplorer-worker:latest
    depends_on:
      - redis
    environment:
      - JSON_RPC_API_URL=http://docker.for.mac.localhost:8545
      - REDIS_URL=redis://redis:6379/0
    networks:
      - knet

networks:
  knet:
