[parity]
chain = "/parity/config/spec.json"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal"]

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "pubsub"]

[footprint]
fat_db = "on"
pruning = "archive"

[network]
reserved_peers = "/parity/config/bootnodes.txt"
